### ISSUE TITLE
CSL样式页面：创建

### ISSUE THREAD

**Issue by northword** [zotero-chinese/website#10]
## 实现

向 https://github.com/redleafnew/Chinese-STD-GB-T-7714-related-csl 申请，由对方仓库 CI 运行时输出一个 JSON 文件供网站构建使用。

- [ ] 样式商店页面
  - [ ] 样式筛选
    - [ ] 顺序编码、作者年代、脚注
    - [ ] 学科分类
    - [ ] 详细特征：作者大小写、作者名全拼、有无标题、期刊全称还是缩写、是否显示 DOI 、是否显示 URL 等
  - [ ] 根据标题、描述搜索
  - [ ] 每一个样式是否需要直接显示示例结果？还是鼠标 hover 时才显示（像官方的）？
- [ ] 样式详情页面
  - [ ] 元数据信息
  - [ ] 示例结果
  - [ ] 下载链接：GitHub、Gitee、CDN
  - [ ] 完整测试结果
  - [ ] 变更历史

## 其他

理想地，redleafnew/Chinese-STD-GB-T-7714-related-csl 的 CI 运行成功时应触发 website 仓库 CI 运行，这样网站数据才能及时更新。

由于 zotero-plugins 仓库会每天定时运行 CI 并触发 website 仓库 CI，所以 redleafnew/Chinese-STD-GB-T-7714-related-csl 仓库不触发 CI 也不是不能接受？

以及：

- redleafnew/Chinese-STD-GB-T-7714-related-csl 位置？
- zotero-chinese/styles 仓库是否需要存档？

**Comment by zepinglee** [comment]
> 以及：
> 
> * redleafnew/Chinese-STD-GB-T-7714-related-csl 位置？
> * zotero-chinese/styles 仓库是否需要存档？

我的建议是在 zotero-chinese/styles 用少量 CSL 样式做一个 prototype，处理好文件的结构，以及详细特征、示例的格式。调通了以后再将 redleafnew/Chinese-STD-GB-T-7714-related-csl 修改为 zotero-chinese/styles 的文件结构，并将仓库 transfer 到 zotero-chinese 替换掉 zotero-chinese/styles。
