### ISSUE TITLE
RSS support

### ISSUE THREAD

**Issue by yiranzhimo** [zotero-chinese/website#41]
Thank you for your contributions to the work. 

I wonder whether there would be an RSS link so we can easily follow any website updates.

Thank you!

**Comment by northword** [comment]
Thank you for your suggestion, we will support RSS in the future.

As this issue is a duplication of #27, we will close this issue, please watch #27 for subsequent updates.

**Comment by northword** [comment]
RSS 已上线，地址为：https://zotero-chinese.com/feed.xml

该地址仅包含所有文档，日期为最后更新日期，不包含插件商店、CSL 商店和转换器商店的更新。
