### ISSUE TITLE
`second-field-align="flush"` 对齐的宽度问题

### ISSUE THREAD

**Issue by zepinglee** [zotero-chinese/website#48]
<https://zotero-cn.github.io/styles/manual-of-legal-citation-multi-lingual/>

<img width="709" alt="Screen Shot 2022-08-22 at 21 50 34" src="https://user-images.githubusercontent.com/12290822/185937483-0ffba1f2-28ae-4a5c-a4df-f0c1ecb97900.png">

目前 `display: flex` 的对齐方式似乎是，每条文献的 label 与内容空固定的距离（0.5 em）。但是当 label 的宽度变化时（比如这里从 9 到 10），右侧内容在整体上就没有对齐了。

更理想的显示效果是，所有 label 使用固定的宽度，即所有 label 宽度的最大值。这样可以使得全部文献右侧内容都对齐。

<img width="700" alt="Screen Shot 2022-08-22 at 21 56 09" src="https://user-images.githubusercontent.com/12290822/185938579-7e5c35b5-ba2f-4786-80d8-94cd491d0966.png">

[`citeproce.makeBibliography()`](https://citeproc-js.readthedocs.io/en/latest/running.html#makebibliography) 返回的第一个参数有个 `maxoffset` 表示 label 的最大字符数，应该可以用于计算 label 的宽度。对于目前的样式，(maxoffset / 2 + 1) em 是个比较合适的值，可以装下 `〔10〕` 这样使用全角六角括号的 label。

**Comment by northword** [comment]
此 issue 仍有问题，待修复：

![image](https://github.com/zotero-chinese/website/assets/44738481/3a205d2a-e672-4a58-949f-336e04880416)
