### ISSUE TITLE
CSL 页面：更多特征描述标签，直接展示预览结果

### ISSUE THREAD

**Issue by northword** [zotero-chinese/website#62]
### Discussed in https://github.com/orgs/zotero-chinese/discussions/204

<div type='discussions-op-text'>

<sup>Originally posted by **@lllo-olll** June 18, 2024</sup>
原页面可根据特征搜索，如“[A]. ”“~ ”“。见”等是我会经常使用的比较显著的条目特征，用来找符合样式的方法。
现新版网址仅可按标题搜索，建议新版网址在搜索栏目推出全部字段搜索，实现特征字段检索功能</div>

**Comment by zepinglee** [comment]
我可以在 CSL 样式那边配合。

顺便一提，“见”的另一种常见的形式是“载”，例如《法学引注手册》。

> 季卫东：《法律程序的意义：对中国法制建设的另一种思考》，载《中国社会科学》1993 年第 1 期。

**Comment by northword** [comment]
我对细致到这种程度的特征确实不了解，我对样式的特征仅限于：作者数量、作者缩写、标题有无、标题大小写、标题斜体、标题书名号、刊名是否缩写、刊名斜体、有无url、有无doi 等。

像这位同学提出的那几个例子我都没有注意过，（我们这个专业领域似乎确实不太关注这些特征，尤其是我们专业的参考文献几乎仅包含期刊文章）

我在想的是，是否有必要把这些特征都列出来，都列出来似乎工作量不小的样子（?）只支持一部分大部分人都用得到的，其余的让网站支持把预览全部显示出来（类似于原来的 README），有需要的可以 ctrl+f 页内搜索，也许更方便。

**Comment by zepinglee** [comment]
我也没完全理解这些标签的使用场景，可能是没有期刊/学校 CSL 样式时寻找接近的版本然后进一步修改？这种情况下我觉得学科的标签更方便吧，比如脚注式社科期刊基本都是参照《中国社会科学》的格式。

> 我在想的是，是否有必要把这些特征都列出来，都列出来似乎工作量不小的样子（?）

单论 [`lib/utils/getTags.ts`](https://github.com/zotero-chinese/styles/blob/f7be7b9ce50839eb22369688789db0f4596e7e03/lib/utils/getTags.ts) 这个脚本的话比较简单，但我不了解网站那边。

**Comment by northword** [comment]
> 但我不了解网站那边

不改变数据结构的话，网站这边不需要修改，网站会遍历所有的 tags  并显示。

> 学科的标签更方便吧，比如脚注式社科期刊基本都是参照《中国社会科学》的格式

就是 ` <category field="generic-base"/>` 这个吗？我回头加上根据这个筛选

**Comment by lllo-olll** [comment]
目前是点选可以进行预览，可以考虑在网页上增加一个一键展开所有预览方便Ctrl+F搜索的按钮嘛

**Comment by zepinglee** [comment]
> 就是 `<category field="generic-base"/>` 这个吗？我回头加上根据这个筛选

嗯是的。

**Comment by northword** [comment]
分步实现此 issue

> 增加一个一键展开所有预览方便Ctrl+F搜索的按钮

https://github.com/zotero-chinese/website/pull/68
